export enum ProviderType {
  GPT = 'GPT',
  ANTHROPIC_GPT = 'ANTHROPIC_GPT',
  ANTHROPIC_NATIVE = 'ANTHROPIC_NATIVE',
  GEMINI = 'GEMINI',
  GEMINI_GPT = 'GEMINI_GPT',
  OPENAI_RESPONSES = 'OPENAI_RESPONSES',
}
