import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy - Echo Platform',
  description:
    'Privacy Policy for the Echo Platform operated by Merit Systems, Inc.',
};

export default function PrivacyPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-8">
      <div className="prose prose-gray dark:prose-invert max-w-none">
        <h1>Echo Platform Privacy Policy</h1>

        <p>
          <strong>Effective Date</strong>: September 9, 2025
          <br />
          <strong>Last Updated</strong>: September 9, 2025
        </p>

        <p>
          This Privacy Policy describes how Merit Systems, Inc. (&quot;Merit
          Systems,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;)
          collects, uses, and protects your information when you use the Echo
          Platform (&quot;Echo,&quot; &quot;the Platform,&quot; or &quot;our
          service&quot;).
        </p>

        <p>
          By using Echo, you agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy should be
          read in conjunction with our Terms of Service.
        </p>

        <hr />

        <h2>1. Information We Collect</h2>

        <h3>Account Information</h3>
        <p>When you create an Echo account, we collect:</p>
        <ul>
          <li>
            <strong>Identity Information</strong>: Name, email address, username
          </li>
          <li>
            <strong>Authentication Data</strong>: Encrypted passwords, OAuth
            tokens from third-party providers (Google, GitHub)
          </li>
          <li>
            <strong>Profile Information</strong>: Profile pictures, bio,
            preferences
          </li>
          <li>
            <strong>Contact Information</strong>: Email address for
            communications and support
          </li>
        </ul>

        <h3>AI Usage Data</h3>
        <p>To provide our AI services and billing, we collect:</p>
        <ul>
          <li>
            <strong>Prompts and Inputs</strong>: The text, questions, or
            instructions you submit to AI models
          </li>
          <li>
            <strong>AI Responses</strong>: The content generated by AI models in
            response to your prompts
          </li>
          <li>
            <strong>Usage Metrics</strong>: Token consumption, model selection,
            response times, costs
          </li>
          <li>
            <strong>API Interactions</strong>: API calls, request/response data,
            error logs
          </li>
          <li>
            <strong>Performance Data</strong>: Response quality, user
            satisfaction ratings
          </li>
        </ul>

        <h3>Application Data</h3>
        <p>If you develop applications using Echo, we collect:</p>
        <ul>
          <li>
            <strong>App Information</strong>: App names, descriptions, settings,
            configuration
          </li>
          <li>
            <strong>Developer Data</strong>: API keys, webhooks, integration
            details
          </li>
          <li>
            <strong>User Analytics</strong>: User engagement, feature usage,
            performance metrics
          </li>
          <li>
            <strong>Revenue Data</strong>: Transaction history, earnings, payout
            information
          </li>
        </ul>

        <h3>Technical Information</h3>
        <p>We automatically collect technical data including:</p>
        <ul>
          <li>
            <strong>Device Information</strong>: Browser type, operating system,
            device identifiers
          </li>
          <li>
            <strong>Connection Data</strong>: IP address, location (city/country
            level), internet service provider
          </li>
          <li>
            <strong>Usage Patterns</strong>: Pages visited, features used, time
            spent, click patterns
          </li>
          <li>
            <strong>System Logs</strong>: Error reports, security events,
            performance metrics
          </li>
        </ul>

        <h3>Financial Information</h3>
        <p>
          For billing and payments, we work with third-party processors to
          collect:
        </p>
        <ul>
          <li>
            <strong>Payment Methods</strong>: Credit/debit card information
            (processed by Stripe)
          </li>
          <li>
            <strong>Billing Information</strong>: Billing address, tax
            identification numbers
          </li>
          <li>
            <strong>Transaction History</strong>: Payment amounts, dates,
            status, invoices
          </li>
          <li>
            <strong>Tax Documentation</strong>: W-9, W-8BEN forms for developers
            receiving payments
          </li>
        </ul>

        <hr />

        <h2>2. How We Use Your Information</h2>

        <h3>Core Service Operations</h3>
        <ul>
          <li>
            <strong>AI Processing</strong>: Forward your prompts to third-party
            AI providers and return responses
          </li>
          <li>
            <strong>Account Management</strong>: Create and maintain your
            account, authenticate access
          </li>
          <li>
            <strong>Billing and Usage</strong>: Track usage, calculate costs,
            process payments, generate invoices
          </li>
          <li>
            <strong>API Services</strong>: Provide access to our APIs and manage
            rate limiting
          </li>
        </ul>

        <h3>Platform Improvement</h3>
        <ul>
          <li>
            <strong>Analytics</strong>: Analyze usage patterns to improve our
            services and user experience
          </li>
          <li>
            <strong>Performance Monitoring</strong>: Monitor system performance
            and optimize response times
          </li>
          <li>
            <strong>Security</strong>: Detect and prevent fraud, abuse, and
            security threats
          </li>
          <li>
            <strong>Product Development</strong>: Develop new features and
            improve existing functionality
          </li>
        </ul>

        <h3>Communications</h3>
        <ul>
          <li>
            <strong>Service Communications</strong>: Account notifications,
            security alerts, service updates
          </li>
          <li>
            <strong>Support</strong>: Respond to your questions and provide
            technical assistance
          </li>
          <li>
            <strong>Marketing</strong>: Send information about new features,
            promotions (with opt-out options)
          </li>
          <li>
            <strong>Legal Compliance</strong>: Fulfill legal obligations and
            enforce our terms
          </li>
        </ul>

        <h3>Developer Services</h3>
        <ul>
          <li>
            <strong>App Analytics</strong>: Provide insights about your
            application&apos;s usage and performance
          </li>
          <li>
            <strong>Revenue Sharing</strong>: Calculate and process payments for
            developers
          </li>
          <li>
            <strong>Integration Support</strong>: Help with API integration and
            troubleshooting
          </li>
        </ul>

        <hr />

        <h2>3. Information Sharing and Third-Party Services</h2>

        <h3>Third-Party AI Providers</h3>
        <p>
          Echo integrates with multiple AI providers. Your prompts and usage
          data are shared with:
        </p>

        <h4>OpenAI</h4>
        <ul>
          <li>
            <strong>Data Shared</strong>: Your prompts, conversation history,
            usage metrics
          </li>
          <li>
            <strong>Purpose</strong>: AI model processing and response
            generation
          </li>
          <li>
            <strong>Privacy Policy</strong>:{' '}
            <a
              href="https://openai.com/privacy/"
              className="text-blue-600 hover:text-blue-800"
            >
              OpenAI Privacy Policy
            </a>
          </li>
          <li>
            <strong>Data Retention</strong>: Per OpenAI&apos;s API data usage
            policies
          </li>
        </ul>

        <h4>Anthropic</h4>
        <ul>
          <li>
            <strong>Data Shared</strong>: Your prompts, conversation history,
            usage metrics
          </li>
          <li>
            <strong>Purpose</strong>: AI model processing and response
            generation
          </li>
          <li>
            <strong>Privacy Policy</strong>:{' '}
            <a
              href="https://www.anthropic.com/privacy/"
              className="text-blue-600 hover:text-blue-800"
            >
              Anthropic Privacy Policy
            </a>
          </li>
          <li>
            <strong>Data Retention</strong>: Per Anthropic&apos;s API data usage
            policies
          </li>
        </ul>

        <h4>Google (Gemini)</h4>
        <ul>
          <li>
            <strong>Data Shared</strong>: Your prompts, conversation history,
            usage metrics
          </li>
          <li>
            <strong>Purpose</strong>: AI model processing and response
            generation
          </li>
          <li>
            <strong>Privacy Policy</strong>:{' '}
            <a
              href="https://policies.google.com/privacy/"
              className="text-blue-600 hover:text-blue-800"
            >
              Google Privacy Policy
            </a>
          </li>
          <li>
            <strong>Data Retention</strong>: Per Google AI API data usage
            policies
          </li>
        </ul>

        <h4>OpenRouter</h4>
        <ul>
          <li>
            <strong>Data Shared</strong>: Your prompts, conversation history,
            usage metrics
          </li>
          <li>
            <strong>Purpose</strong>: AI model processing and response
            generation
          </li>
          <li>
            <strong>Privacy Policy</strong>:{' '}
            <a
              href="https://openrouter.ai/privacy"
              className="text-blue-600 hover:text-blue-800"
            >
              OpenRouter Privacy Policy
            </a>
          </li>
          <li>
            <strong>Data Retention</strong>: Per OpenRouter&apos;s API data
            usage policies
          </li>
        </ul>

        <h3>Payment Processors</h3>

        <h4>Stripe (Payment Processing)</h4>
        <ul>
          <li>
            <strong>Data Shared</strong>: Payment information, billing details,
            transaction data
          </li>
          <li>
            <strong>Purpose</strong>: Process payments, handle subscriptions,
            manage billing
          </li>
          <li>
            <strong>Privacy Policy</strong>:{' '}
            <a
              href="https://stripe.com/privacy"
              className="text-blue-600 hover:text-blue-800"
            >
              Stripe Privacy Policy
            </a>
          </li>
        </ul>

        <h4>Terminal (Payout Processing)</h4>
        <ul>
          <li>
            <strong>Data Shared</strong>: Developer earnings, tax information,
            bank details
          </li>
          <li>
            <strong>Purpose</strong>: Process payouts to developers, handle tax
            compliance
          </li>
          <li>
            <strong>Privacy Policy</strong>:{' '}
            <a
              href="https://merit.systems/privacy"
              className="text-blue-600 hover:text-blue-800"
            >
              Terminal Privacy Policy
            </a>
          </li>
        </ul>

        <h3>Analytics and Infrastructure</h3>

        <h4>Vercel (Hosting and Analytics)</h4>
        <ul>
          <li>
            <strong>Data Shared</strong>: Usage analytics, performance metrics,
            error logs
          </li>
          <li>
            <strong>Purpose</strong>: Host our application, provide performance
            insights
          </li>
          <li>
            <strong>Privacy Policy</strong>:{' '}
            <a
              href="https://vercel.com/legal/privacy-policy"
              className="text-blue-600 hover:text-blue-800"
            >
              Vercel Privacy Policy
            </a>
          </li>
        </ul>

        <h4>PostHog (Product Analytics)</h4>
        <ul>
          <li>
            <strong>Data Shared</strong>: User behavior, feature usage,
            anonymized metrics
          </li>
          <li>
            <strong>Purpose</strong>: Understand product usage, improve user
            experience
          </li>
          <li>
            <strong>Privacy Policy</strong>:{' '}
            <a
              href="https://posthog.com/privacy"
              className="text-blue-600 hover:text-blue-800"
            >
              PostHog Privacy Policy
            </a>
          </li>
        </ul>

        <h3>When We Share Information</h3>
        <p>We may share your information in these circumstances:</p>
        <ul>
          <li>
            <strong>Service Providers</strong>: With third parties who help us
            operate our platform
          </li>
          <li>
            <strong>Legal Requirements</strong>: When required by law, court
            order, or government request
          </li>
          <li>
            <strong>Safety and Security</strong>: To protect our users,
            platform, or public safety
          </li>
          <li>
            <strong>Business Transfers</strong>: In connection with mergers,
            acquisitions, or asset sales
          </li>
          <li>
            <strong>With Your Consent</strong>: When you explicitly authorize us
            to share information
          </li>
        </ul>

        <h3>What We Don&apos;t Share</h3>
        <p>We do not:</p>
        <ul>
          <li>Sell your personal information to third parties</li>
          <li>
            Share your prompts with other Echo users (unless you explicitly
            share them)
          </li>
          <li>Use your data to train our own AI models</li>
          <li>Share more information than necessary to provide our services</li>
        </ul>

        <hr />

        <h2>4. Data Security and Protection</h2>

        <h3>Security Measures</h3>
        <p>We implement multiple layers of security to protect your data:</p>

        <h4>Technical Safeguards</h4>
        <ul>
          <li>
            <strong>Encryption</strong>: Data encrypted in transit (TLS 1.3) and
            at rest (AES-256)
          </li>
          <li>
            <strong>Authentication</strong>: Multi-factor authentication
            support, secure password policies
          </li>
          <li>
            <strong>Access Controls</strong>: Role-based access, principle of
            least privilege
          </li>
          <li>
            <strong>API Security</strong>: Rate limiting, API key management,
            secure endpoints
          </li>
        </ul>

        <h4>Infrastructure Security</h4>
        <ul>
          <li>
            <strong>Cloud Security</strong>: AWS/Vercel security controls,
            secure data centers
          </li>
          <li>
            <strong>Network Security</strong>: Firewalls, intrusion detection,
            DDoS protection
          </li>
          <li>
            <strong>Monitoring</strong>: 24/7 security monitoring, anomaly
            detection
          </li>
          <li>
            <strong>Incident Response</strong>: Established procedures for
            security incidents
          </li>
        </ul>

        <h4>Operational Security</h4>
        <ul>
          <li>
            <strong>Employee Training</strong>: Security awareness training for
            all staff
          </li>
          <li>
            <strong>Background Checks</strong>: Screening for employees with
            data access
          </li>
          <li>
            <strong>Regular Audits</strong>: Security assessments and
            penetration testing
          </li>
          <li>
            <strong>Compliance</strong>: SOC 2 Type II compliance (in progress)
          </li>
        </ul>

        <h3>Data Breach Response</h3>
        <p>In the event of a data breach, we will:</p>
        <ul>
          <li>Immediately investigate and contain the breach</li>
          <li>Notify affected users within 72 hours when legally required</li>
          <li>Provide detailed information about what data was affected</li>
          <li>Offer guidance on protective steps you can take</li>
          <li>Report to relevant authorities as required by law</li>
        </ul>

        <hr />

        <h2>5. Data Retention and Deletion</h2>

        <h3>Retention Periods</h3>

        <h4>Account Data</h4>
        <ul>
          <li>
            <strong>Active Accounts</strong>: Retained while your account is
            active
          </li>
          <li>
            <strong>Closed Accounts</strong>: Personal data deleted within 30
            days of account closure
          </li>
          <li>
            <strong>Legal Hold</strong>: May be retained longer if required for
            legal proceedings
          </li>
        </ul>

        <h4>AI Usage Data</h4>
        <ul>
          <li>
            <strong>Prompts and Responses</strong>: Retained for 90 days for
            debugging and billing
          </li>
          <li>
            <strong>Usage Metrics</strong>: Retained for 2 years for analytics
            and billing history
          </li>
          <li>
            <strong>Error Logs</strong>: Retained for 1 year for system
            improvement
          </li>
        </ul>

        <h4>Financial Data</h4>
        <ul>
          <li>
            <strong>Payment Records</strong>: Retained for 7 years for tax and
            legal compliance
          </li>
          <li>
            <strong>Tax Documents</strong>: Retained as required by applicable
            tax laws
          </li>
          <li>
            <strong>Transaction History</strong>: Retained for 5 years for
            dispute resolution
          </li>
        </ul>

        <h4>Analytics Data</h4>
        <ul>
          <li>
            <strong>Aggregated Analytics</strong>: Retained indefinitely
            (anonymized)
          </li>
          <li>
            <strong>Individual Usage Patterns</strong>: Retained for 2 years
          </li>
          <li>
            <strong>Security Logs</strong>: Retained for 1 year
          </li>
        </ul>

        <h3>Data Deletion</h3>
        <p>You can request deletion of your data by:</p>
        <ul>
          <li>Using account deletion features in your dashboard</li>
          <li>
            Contacting us at{' '}
            <a
              href="mailto:privacy@merit.systems"
              className="text-blue-600 hover:text-blue-800"
            >
              privacy@merit.systems
            </a>
          </li>
          <li>Following our data subject rights procedures (see Section 7)</li>
        </ul>

        <p>
          <strong>Note</strong>: Some data may be retained for legal compliance
          even after deletion requests.
        </p>

        <hr />

        <h2>6. International Data Transfers</h2>

        <h3>Global Operations</h3>
        <p>
          Echo operates globally, and your data may be transferred to and
          processed in:
        </p>
        <ul>
          <li>
            <strong>United States</strong>: Primary data processing and storage
          </li>
          <li>
            <strong>European Union</strong>: EU users&apos; data may be
            processed in EU data centers
          </li>
          <li>
            <strong>Third-Party Locations</strong>: AI providers and service
            providers may process data globally
          </li>
        </ul>

        <h3>Transfer Safeguards</h3>
        <p>
          When transferring data internationally, we ensure appropriate
          safeguards:
        </p>
        <ul>
          <li>
            <strong>Adequacy Decisions</strong>: Transfers to countries with
            adequate data protection
          </li>
          <li>
            <strong>Standard Contractual Clauses</strong>: EU-approved
            contractual protections
          </li>
          <li>
            <strong>Binding Corporate Rules</strong>: Internal policies ensuring
            consistent protection
          </li>
          <li>
            <strong>Certification Schemes</strong>: Privacy Shield successors
            and similar frameworks
          </li>
        </ul>

        <h3>Data Processing Locations</h3>

        <h4>AI Providers</h4>
        <ul>
          <li>
            <strong>OpenAI</strong>: Primarily US-based processing
          </li>
          <li>
            <strong>Anthropic</strong>: US-based processing
          </li>
          <li>
            <strong>Google</strong>: Global processing, may include EU data
            centers
          </li>
          <li>
            <strong>OpenRouter</strong>: Variable locations depending on
            selected models
          </li>
        </ul>

        <h4>Infrastructure Providers</h4>
        <ul>
          <li>
            <strong>Vercel</strong>: Global edge network, data residency options
            available
          </li>
          <li>
            <strong>AWS</strong>: Multiple regions, EU data residency for EU
            users
          </li>
        </ul>

        <hr />

        <h2>7. Your Privacy Rights</h2>

        <h3>General Rights</h3>
        <p>Depending on your location, you may have the following rights:</p>

        <h4>Access Rights</h4>
        <ul>
          <li>
            <strong>Data Access</strong>: Request copies of your personal data
          </li>
          <li>
            <strong>Processing Information</strong>: Learn how we process your
            data
          </li>
          <li>
            <strong>Third-Party Sharing</strong>: Information about data sharing
            with third parties
          </li>
        </ul>

        <h4>Control Rights</h4>
        <ul>
          <li>
            <strong>Rectification</strong>: Correct inaccurate or incomplete
            data
          </li>
          <li>
            <strong>Deletion</strong>: Request deletion of your personal data
            (&quot;right to be forgotten&quot;)
          </li>
          <li>
            <strong>Portability</strong>: Export your data in a machine-readable
            format
          </li>
          <li>
            <strong>Restriction</strong>: Limit how we process your data
          </li>
        </ul>

        <h4>Objection Rights</h4>
        <ul>
          <li>
            <strong>Processing Objection</strong>: Object to processing based on
            legitimate interests
          </li>
          <li>
            <strong>Marketing Opt-Out</strong>: Unsubscribe from marketing
            communications
          </li>
          <li>
            <strong>Automated Processing</strong>: Object to automated
            decision-making
          </li>
        </ul>

        <h3>Region-Specific Rights</h3>

        <h4>European Union (GDPR)</h4>
        <p>
          EU users have enhanced rights under the General Data Protection
          Regulation:
        </p>
        <ul>
          <li>Right to data protection by design and default</li>
          <li>Right to lodge complaints with supervisory authorities</li>
          <li>Enhanced consent requirements for data processing</li>
          <li>Right to withdraw consent at any time</li>
        </ul>

        <h4>California (CCPA/CPRA)</h4>
        <p>
          California residents have specific rights under state privacy laws:
        </p>
        <ul>
          <li>Right to know what personal information is collected</li>
          <li>Right to delete personal information</li>
          <li>Right to opt-out of the sale of personal information</li>
          <li>Right to non-discrimination for exercising privacy rights</li>
        </ul>

        <h4>Other Jurisdictions</h4>
        <p>
          We extend similar privacy rights to users in other jurisdictions with
          applicable privacy laws.
        </p>

        <h3>Exercising Your Rights</h3>
        <p>To exercise your privacy rights:</p>
        <ol>
          <li>
            <strong>Account Settings</strong>: Many rights can be exercised
            through your account dashboard
          </li>
          <li>
            <strong>Privacy Request Form</strong>: Submit requests through our
            privacy portal
          </li>
          <li>
            <strong>Email</strong>: Contact us at{' '}
            <a
              href="mailto:privacy@merit.systems"
              className="text-blue-600 hover:text-blue-800"
            >
              privacy@merit.systems
            </a>
          </li>
          <li>
            <strong>Identity Verification</strong>: We may require identity
            verification for security
          </li>
        </ol>

        <p>
          We will respond to valid requests within 30 days (or as required by
          applicable law).
        </p>

        <hr />

        <h2>8. Cookies and Tracking Technologies</h2>

        <h3>Types of Cookies We Use</h3>

        <h4>Essential Cookies</h4>
        <ul>
          <li>
            <strong>Authentication</strong>: Keep you logged in during your
            session
          </li>
          <li>
            <strong>Security</strong>: Prevent cross-site request forgery and
            other attacks
          </li>
          <li>
            <strong>Load Balancing</strong>: Ensure optimal server performance
          </li>
          <li>
            <strong>Preferences</strong>: Remember your settings (theme,
            language)
          </li>
        </ul>

        <h4>Analytics Cookies</h4>
        <ul>
          <li>
            <strong>Usage Analytics</strong>: Understand how users interact with
            our platform
          </li>
          <li>
            <strong>Performance Monitoring</strong>: Track page load times and
            errors
          </li>
          <li>
            <strong>Feature Usage</strong>: Measure adoption of new features
          </li>
        </ul>

        <h4>Marketing Cookies (Optional)</h4>
        <ul>
          <li>
            <strong>Conversion Tracking</strong>: Measure effectiveness of
            marketing campaigns
          </li>
          <li>
            <strong>Retargeting</strong>: Show relevant ads on other websites
          </li>
          <li>
            <strong>Social Media Integration</strong>: Enable sharing and social
            login features
          </li>
        </ul>

        <h3>Third-Party Cookies</h3>
        <p>We may use third-party cookies from:</p>
        <ul>
          <li>
            <strong>Vercel Analytics</strong>: Performance and usage analytics
          </li>
          <li>
            <strong>PostHog</strong>: Product analytics and user behavior
            tracking
          </li>
          <li>
            <strong>Stripe</strong>: Payment processing and fraud prevention
          </li>
          <li>
            <strong>OAuth Providers</strong>: Google, GitHub for authentication
          </li>
        </ul>

        <h3>Managing Cookies</h3>
        <p>You can control cookies through:</p>
        <ul>
          <li>
            <strong>Browser Settings</strong>: Disable or limit cookies in your
            browser
          </li>
          <li>
            <strong>Cookie Preferences</strong>: Use our cookie consent manager
          </li>
          <li>
            <strong>Opt-Out Tools</strong>: Use industry opt-out tools for
            advertising cookies
          </li>
          <li>
            <strong>Private Browsing</strong>: Use incognito/private browsing
            modes
          </li>
        </ul>

        <p>
          <strong>Note</strong>: Disabling essential cookies may affect platform
          functionality.
        </p>

        <hr />

        <h2>9. Children&apos;s Privacy</h2>

        <h3>Age Restrictions</h3>
        <p>
          Echo is not intended for use by children under 18 years of age. We:
        </p>
        <ul>
          <li>
            Do not knowingly collect personal information from children under 18
          </li>
          <li>Require users to confirm they are at least 18 years old</li>
          <li>
            Will delete any information we discover was collected from children
          </li>
          <li>
            Encourage parents to monitor their children&apos;s internet usage
          </li>
        </ul>

        <h3>Parental Controls</h3>
        <p>If you believe your child has provided information to Echo:</p>
        <ul>
          <li>
            Contact us immediately at{' '}
            <a
              href="mailto:privacy@merit.systems"
              className="text-blue-600 hover:text-blue-800"
            >
              privacy@merit.systems
            </a>
          </li>
          <li>We will promptly delete the account and associated data</li>
          <li>We will implement measures to prevent future access</li>
        </ul>

        <h3>Educational Use</h3>
        <p>For educational institutions using Echo:</p>
        <ul>
          <li>
            Institutions must verify user ages and obtain appropriate consents
          </li>
          <li>Enhanced privacy protections apply to educational data</li>
          <li>Compliance with FERPA and similar education privacy laws</li>
        </ul>

        <hr />

        <h2>10. Changes to This Privacy Policy</h2>

        <h3>Updates and Notifications</h3>
        <p>We may update this Privacy Policy to:</p>
        <ul>
          <li>Reflect changes in our services or business practices</li>
          <li>Comply with new legal requirements</li>
          <li>Improve our privacy practices</li>
          <li>Address user feedback and concerns</li>
        </ul>

        <h3>How We Notify You</h3>
        <p>For material changes, we will notify you by:</p>
        <ul>
          <li>
            <strong>Email</strong>: Notice sent to your registered email address
          </li>
          <li>
            <strong>Platform Notice</strong>: Prominent notice on our platform
          </li>
          <li>
            <strong>In-App Notification</strong>: Alert when you next use Echo
          </li>
          <li>
            <strong>Version History</strong>: Maintain a changelog of policy
            updates
          </li>
        </ul>

        <h3>Effective Date of Changes</h3>
        <p>Changes become effective:</p>
        <ul>
          <li>
            <strong>Immediately</strong>: For clarifications that don&apos;t
            change your rights
          </li>
          <li>
            <strong>30 Days</strong>: For material changes affecting data
            processing
          </li>
          <li>
            <strong>Upon Consent</strong>: For changes requiring explicit
            consent
          </li>
        </ul>

        <p>
          Your continued use of Echo after changes become effective constitutes
          acceptance of the updated Privacy Policy.
        </p>

        <hr />

        <h2>11. Contact Information and Data Protection</h2>

        <h3>Privacy Team Contact</h3>
        <p>For privacy-related questions, concerns, or requests:</p>

        <p>
          <strong>Privacy Officer</strong>
          <br />
          Merit Systems, Inc.
          <br />
          Email:{' '}
          <a
            href="mailto:privacy@merit.systems"
            className="text-blue-600 hover:text-blue-800"
          >
            privacy@merit.systems
          </a>
          <br />
          Address: 224 West 35th Street, Ste 500 #2218, New York, NY 10001
        </p>

        <h3>Data Protection Representative (EU)</h3>
        <p>
          For EU users, our EU Data Protection Representative can be contacted
          at:
          <br />
          Email:{' '}
          <a
            href="mailto:eu-privacy@merit.systems"
            className="text-blue-600 hover:text-blue-800"
          >
            eu-privacy@merit.systems
          </a>
        </p>

        <h3>Supervisory Authority</h3>
        <p>
          EU users have the right to lodge complaints with their local
          supervisory authority regarding our data processing activities.
        </p>

        <h3>Response Times</h3>
        <p>We aim to respond to privacy inquiries within:</p>
        <ul>
          <li>
            <strong>General Questions</strong>: 5 business days
          </li>
          <li>
            <strong>Data Subject Requests</strong>: 30 days (as required by law)
          </li>
          <li>
            <strong>Urgent Security Matters</strong>: 24 hours
          </li>
        </ul>

        <hr />

        <h2>12. Specific Privacy Practices for AI Services</h2>

        <h3>AI Prompt Handling</h3>
        <p>When you submit prompts to AI models through Echo:</p>

        <h4>Data Flow</h4>
        <ol>
          <li>
            <strong>Prompt Reception</strong>: Your prompt is received and
            logged by Echo
          </li>
          <li>
            <strong>Pre-Processing</strong>: We may apply content filtering and
            safety checks
          </li>
          <li>
            <strong>Third-Party Transmission</strong>: Prompt is sent to the
            selected AI provider
          </li>
          <li>
            <strong>Response Handling</strong>: AI response is received and
            returned to you
          </li>
          <li>
            <strong>Usage Tracking</strong>: Token usage and costs are
            calculated and stored
          </li>
        </ol>

        <h4>Prompt Privacy Considerations</h4>
        <ul>
          <li>
            <strong>Visibility</strong>: Your prompts are visible to the AI
            provider you select
          </li>
          <li>
            <strong>Retention</strong>: AI providers have their own data
            retention policies
          </li>
          <li>
            <strong>Training</strong>: Some providers may use API data for model
            improvement
          </li>
          <li>
            <strong>Privacy Options</strong>: Some providers offer enhanced
            privacy modes
          </li>
        </ul>

        <h3>Data Minimization</h3>
        <p>We practice data minimization by:</p>
        <ul>
          <li>Only collecting data necessary for service operation</li>
          <li>Regularly purging old prompt data</li>
          <li>Anonymizing analytics data where possible</li>
          <li>Limiting employee access to personal data</li>
        </ul>

        <h3>AI Model Selection and Privacy</h3>
        <p>Different AI providers have different privacy practices:</p>

        <h4>Privacy-First Options</h4>
        <ul>
          <li>Some providers offer models with enhanced privacy protections</li>
          <li>Options for processing without data retention</li>
          <li>Models that don&apos;t use API data for training</li>
        </ul>

        <h4>User Control</h4>
        <ul>
          <li>Choose AI providers based on their privacy practices</li>
          <li>Opt for providers with stronger data protection</li>
          <li>Understand trade-offs between features and privacy</li>
        </ul>

        <hr />

        <p className="italic">
          This Privacy Policy is designed to be transparent about our data
          practices. If you have any questions or concerns, please don&apos;t
          hesitate to contact our privacy team at{' '}
          <a
            href="mailto:privacy@merit.systems"
            className="text-blue-600 hover:text-blue-800"
          >
            privacy@merit.systems
          </a>
          .
        </p>

        <p className="italic font-bold">
          By using Echo, you acknowledge that you have read, understood, and
          agree to this Privacy Policy.
        </p>
      </div>
    </div>
  );
}
